version: "3"
services:
  docs:
    build: .
    image: redbrick/docs
    networks:
      - web
    volumes:
      -  /usr/src/app
    labels:
    - "traefik.backend=docs"
    - "traefik.docker.network=web"
    - "traefik.frontend.rule=Host:docs.redbrick.dcu.ie"
    - "traefik.enable=true"
    - "traefik.port=8000"

  test:
    image: 18fgsa/html-proofer
    command: site --allow-hash-href --check-html --empty-alt-ignore --disable-external
    volumes:
      -  /site:/site

networks:
  web:
    external: true
