site_name: Redbrick Docs
theme: readthedocs
repo_url: https://github.com/redbrick/docs
pages:
 - Home: index.md
 - Services:
   - hey: hey.md
   - Mercurial: hg.md
   - Git: git.md
   - IRC: irc.md
 - 10.04-services-checklist: 10.04-services-checklist.md
 - 10.04move: 10.04move.md
 - 2011-to-do: 2011-to-do.md
 - abuse: abuse.md
 - addldap: addldap.md
 - anyterm: anyterm.md
 - apachemodules: apachemodules.md
 - apacheondeathray: apacheondeathray.md
 - apacheonmurphy: apacheonmurphy.md
 - apachesolaris: apachesolaris.md
 - backport-packages: backport-packages.md
 - bitlbee: bitlbee.md
 - carbon: carbon.md
 - carbonanddeathray: carbonanddeathray.md
 - carbonrebootwarning: carbonrebootwarning.md
 - ceilingcat: ceilingcat.md
 - ciscoios: ciscoios.md
 - committeechangeover: committeechangeover.md
 - compilingxen: compilingxen.md
 - ctyi: ctyi.md
 - cynic: cynic.md
 - cynic_dpkg: cynic_dpkg.md
 - cynic_setup_zones: cynic_setup_zones.md
 - cynicdebian: cynicdebian.md
 - cynicrscaccess: cynicrscaccess.md
 - daniel: daniel.md
 - deathray: deathray.md
 - dirvish: dirvish.md
 - dirvish_tutorial: dirvish_tutorial.md
 - dnsaddressspace: dnsaddressspace.md
 - docs_mirror_script: docs_mirror_script.md
 - dovecot: dovecot.md
 - dracaccess: dracaccess.md
 - exim: exim.md
 - exim_solaris: exim_solaris.md
 - faststorage: faststorage.md
 - gpgkeys: gpgkeys.md
 - gratuitousarp: gratuitousarp.md
 - icecast2: icecast2.md
 - imapupdatingcert: imapupdatingcert.md
 - irc_operator: irc_operator.md
 - ircproxy: ircproxy.md
 - jabber: jabber.md
 - kernel-module-blacklist: kernel-module-blacklist.md
 - ldap: ldap.md
 - ldapchshchfn: ldapchshchfn.md
 - ldapsetup: ldapsetup.md
 - library_migration: library_migration.md
 - lofiadm: lofiadm.md
 - mail_setup: mail_setup.md
 - mailman: mailman.md
 - mainaddressspace: mainaddressspace.md
 - minerva: minerva.md
 - minervastorage: minervastorage.md
 - modifyingldap: modifyingldap.md
 - munger: munger.md
 - munin: munin.md
 - murphy-disabled_services: murphy-disabled_services.md
 - murphy-install-log: murphy-install-log.md
 - murphy-jumpstart: murphy-jumpstart.md
 - murphy-zones: murphy-zones.md
 - murphy: murphy.md
 - murphyalomaccess: murphyalomaccess.md
 - murphyliveupgrade: murphyliveupgrade.md
 - murphymysqlclientbug: murphymysqlclientbug.md
 - murphypython: murphypython.md
 - murphysolaris: murphysolaris.md
 - mysql: mysql.md
 - nagios: nagios.md
 - nagios_to_do: nagios_to_do.md
 - networksetup: networksetup.md
 - new_admin_to_do: new_admin_to_do.md
 - newboard: newboard.md
 - newinstalls: newinstalls.md
 - news: news.md
 - newsoverviewfix: newsoverviewfix.md
 - nfs: nfs.md
 - obeliskstuff: obeliskstuff.md
 - openports: openports.md
 - orphan_pages: orphan_pages.md
 - ossec: ossec.md
 - paphos_migration: paphos_migration.md
 - pass-change: pass-change.md
 - passwd: passwd.md
 - peepd: peepd.md
 - phpsolaris: phpsolaris.md
 - pike: pike.md
 - pkgsrc: pkgsrc.md
 - policies: policies.md
 - post_mortem_mar16: post_mortem_mar16.md
 - post_powercut: post_powercut.md
 - postgres: postgres.md
 - project-ideas: project-ideas.md
 - pubcookie: pubcookie.md
 - putty: putty.md
 - rbscripts: rbscripts.md
 - rbusers: rbusers.md
 - rbvm: rbvm.md
 - rbvmctl: rbvmctl.md
 - redbrick-apt: redbrick-apt.md
 - redbrick.dcu.ie: redbrick.dcu.ie.md
 - redbrick_solaris_package_manager: redbrick_solaris_package_manager.md
 - rrs: rrs.md
 - severus: severus.md
 - severus_vpn: severus_vpn.md
 - severuscolocation: severuscolocation.md
 - sprout-serial: sprout-serial.md
 - sprout: sprout.md
 - ssl: ssl.md
 - stuff_that_needs_doing_before_we_can_buy_new_servers: stuff_that_needs_doing_before_we_can_buy_new_servers.md
 - suphp: suphp.md
 - switch: switch.md
 - testing: testing.md
 - the_pdus: the_pdus.md
 - thunder: thunder.md
 - ticketing: ticketing.md
 - to_do_1502: to_do_1502.md
 - tomcat-murphy: tomcat-murphy.md
 - tunnel.redbrick.dcu.ie: tunnel.redbrick.dcu.ie.md
 - ubuntukernel: ubuntukernel.md
 - unifiedmotd: unifiedmotd.md
 - ups: ups.md
 - vmaddressspace: vmaddressspace.md
 - vmserverstuff: vmserverstuff.md
 - warmstart: warmstart.md
 - webchat: webchat.md
 - worf_plan: worf_plan.md
 - x4140ilom: x4140ilom.md
